repos:
  # Standard out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # Ruff linter (blazing fast alternative to flake8/pylint)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [ --fix ]
